# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: "v2.37.3"
    hooks:
      - id: pyupgrade
        args: [--py310-plus]
